version: "3"
services:
  app:
    build: .
    container_name: flask-app
    volumes:
      - ./app:/usr/src/app
      - socket:/tmp
    command: uwsgi --ini app.ini

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket:
  
