version: "3"
services:
  app:
    build: ./app/
    image: flask-image
    container_name: flask-app
    ports:
      - "5001:5000"
  
    volumes:
      - ./app:/usr/src/app
      # - socket:/tmp
    # command: uwsgi --ini app.ini
    # command: uwsgi ./app/app
    command: flask run --host=0.0.0.0
    # command: uwsgi --http=0.0.0.0:8080 --wsgi-file=wsgi.py  --callable=app

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket:
  
