version: "3"
services:
  app:
    build: ./app/
    image: flask-image
    container_name: flask-app
    ports:
      - "5001:5000"
  
    volumes:
      - ./app:/usr/src/app
      - socket:/tmp
    #uwsgiでアプリを起動するコマンド
    command: uwsgi --ini app.ini
    # flaskでアプリを起動するコマンド
    # command: flask run --host=0.0.0.0

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket:
  
